var myArray = ["ABDUL HAYAT BIN MAT ZALI",
"AHMAD SYUKRI ZAIN BIN MOHD SALLEH",
"AIMAN BIN MD YUSOF",
"AMAN SHAH BIN ABDUL SATAR",
"AMRAN BIN ASHAARI",
"AMRAN BIN EBERAHIM",
"ARNI BINTI HASHIM",
"AZLINOR BIN SABLI",
"AZLIZAN SHAHRUL ZAMAN",
"FAIZAL BIN MOHAMAD",
"FAIZAN NORHAYATI BINTI OTHMAN",
"FARID BIN ISMAIL",
"HAFIDZ BIN NASRUDDIN",
"HARUL IZWAN BIN ABD HAMID",
"HASZANORAISYAH BINTI HASHIM",
"HEZLINDA BINTI ABD. RAHMAN",
"INTAN HAFINA BINTI ISMAIL",
"JANE JASMIN BINTI BENJAMIN YUEN",
"KAMARUZAMAN BIN ABDOL RAHIM",
"KHAIRUN NADYA BINTI NIKMAN",
"MAIZATUNNISA BIN MOHTAR",
"MD FAISHAL BIN KABUN",
"MOHAMAD HAFIZZ BIN ABU ADAM",
"MOHAMAD RANIZA BIN ABD. HAMID",
"MOHAMMAD IZUAN BIN SAUD",
"MOHD ASYRAF BIN MOHD ARIFFIN",
"MOHD FADZIL BIN HASIM",
"MOHD FAIZUL BIN SULIMAN",
"MOHD IZUAN BIN MOHD HASHIM",
"MOHD MUSABRI BIN SHAHAROM",
"MOHD ROHALLAH JURAIJ BIN SHAFAWI",
"MOHD SHAH RIDZUAN BIN MAARIP",
"MOHD SUFIAN BIN MD OLAN",
"MOHD SYAFID BIN ABDULLAH",
"MOKTI BIN SAIDIN",
"MUHAMMAD AMMAR BIN MOHD AFFANDI",
"MUHAMMAD SHURAZI BIN SUKHUR",
"MUZAIDI BIN MARJUKI @ MARZUKI",
"NADIAH BINTI MD NORDIN",
"NINI RONNA BINTI RASHIFF",
"NOOR AZMAN BIN ABDUL KASIM",
"NOR ANIZA BINTI BAHARUDIN",
"NOR AZIRA BINTI ISMAIL",
"NOR DALINA BINTI MAHMOOD",
"NORAZLEEN BINTI ABDULLAH",
"ROSMAIDI BIN RIMIN",
"RUBY HASLINDA BINTI JUDIN",
"SEPRIYANDI BIN AGUSR",
"SHAHAMIZAN BIN MD SHAHUDIN",
"SHAHARUDIN BIN DAHALAN",
"SITI SYAKIRA BINTI ABDUL JALIL",
"SYALINDA BINTI ABU HASSAN AL SHAARI",
"WAN ZULKEFLI BIN ABU BAKAR",
"YURAMZAN BIN YUSOF",
"ZABIBAH BINTI SAMAT",
"ZAKARIA BIN MAT ALI",
"ZAKRI BIN ZAINAL"];

function stopRoll() {
    greeting.innerHTML = 'Tahniah Kepada '
    var rand = myArray[Math.floor(Math.random() * myArray.length)]; nama.innerHTML = '<strong>' + rand + '</strong> !!!';
}
function resetNama() {
    nama.innerHTML = '<h2 class="alert alert-info" role="alert">Siapakah peserta bertuah pada hari ini?</h2>';
}

function roll() {
    var ct = $("#nama").data("term") || 0;
    $("#nama").data("term", ct == myArray.length - 1 ? 0 : Math.floor(Math.random() * myArray.length)).text(myArray[ct]).fadeIn(200).fadeOut(200, roll);
}
